EN = {
    "account": "Account",
    "tab_graphics": "Graphics",
    "tab_gameplay": "Gameplay",
    "tab_audio": "Audio",
    "tab_launch": "Launch",
    "tab_cheats": "Cheats",
    "tab_system": "System",
    "tab_network": "Network",
    "tab_settings": "Settings",
    "graphics_presets": "Graphics Presets",
    "preset_max_fps": "Max FPS",
    "preset_balanced": "Balanced",
    "preset_quality": "Quality",
    "visual_settings": "Visual Settings",
    "draw_distance": "Draw Distance",
    "camera_fog": "Camera Fog",
    "texture_quality": "Texture Quality",
    "anti_aliasing": "Anti-Aliasing",
    "shadow_quality": "Shadow Quality",
    "fps_limit": "FPS Limit (0 = off)",
    "effects": "Effects",
    "shadows": "Shadows",
    "bloom": "Bloom",
    "ssao": "SSAO",
    "motion_blur": "Motion Blur",
    "ambient_occlusion": "Ambient Occlusion",
    "depth_of_field": "Depth of Field",
    "chromatic_aberration": "Chromatic Aberration",
    "vsync": "VSync",
    "show_blood": "Show Blood",
    "ragdoll_cleanup": "Ragdoll Cleanup",
    "flashlight_shadows": "Flashlight Shadows",
    "ragdoll_limit": "Ragdoll Limit",
    "audio_levels": "Audio Levels",
    "master_volume": "Master Volume",
    "sfx_volume": "SFX Volume",
    "voice_volume": "Voice Volume",
    "music_volume": "Music Volume",
    "voice": "Voice",
    "noise_suppression": "Noise Suppression",
    "noise_suppression_desc": "Disable for lower CPU usage",
    "voice_ns_level": "Voice NS Level",
    "steam_launch_options": "Steam Launch Options",
    "force_dx11": "Force DirectX 11",
    "fastest_quality": "Fastest Quality",
    "windowed_borderless": "Windowed Borderless",
    "disable_gpu_skinning": "Disable GPU Skinning",
    "force_vulkan": "Force Vulkan",
    "force_opengl": "Force OpenGL",
    "no_log": "No Log Files",
    "no_joy": "Disable Joystick",
    "high_priority_launch": "High Priority",
    "malloc_system": "System Allocator",
    "use_all_cores": "Use All Cores",
    "custom_args": "Custom Arguments",
    "save_launch_options": "Save Launch Options",
    "launch_game": "Launch Game",
    "layer1_file_nukes": "Layer 1 � File Nukes",
    "safe": "SAFE",
    "layer1_desc": "Modify game files on disk BEFORE launch. Anti-cheat isn't running yet � it can't see this. Steam may revert files on update; re-apply after patches.",
    "anticheat_bypass": "Anti-Cheat Bypass",
    "anticheat_bypass_desc": "Replace SL-AC.dll with a dummy. AC never loads.",
    "disable_crash_handler": "Disable Crash Handler",
    "disable_crash_handler_desc": "Prevents UnityCrashHandler from running. Less background noise.",
    "disable_analytics": "Disable Analytics",
    "disable_analytics_desc": "Removes Unity analytics DLL. Stops telemetry collection.",
    "bootconfig_nuke": "Boot.config Nuke",
    "bootconfig_nuke_desc": "Aggressive GC, no single-instance lock, multi-threaded renderer.",
    "ggm_destroyer": "GlobalGameManagers Destroyer",
    "ggm_destroyer_desc": "Binary-patch Unity QualitySettings. Zero shadows, no AA, no vsync, aggressive LOD.",
    "layer1b_hex": "Layer 1b � GameAssembly Hex",
    "nuclear": "NUCLEAR",
    "layer1b_desc": "Hex-patches the compiled IL2CPP native binary (GameAssembly.dll) on disk. Wrong pattern = instant crash on startup. Update patterns via x64dbg before use.",
    "analyze_binary": "Analyze Binary",
    "apply_hex_patches": "Apply Hex Patches",
    "restore_backup": "Restore Backup",
    "layer2_launch": "Layer 2 � Launch Stealth",
    "layer2_desc": "One-click preparation + launch. Optionally self-destructs this tweaker so no process remains in memory for the anti-cheat to scan.",
    "patch_ac": "Patch Anti-Cheat",
    "patch_ac_desc": "Include SL-AC.dll replacement",
    "patch_boot": "Patch Boot.config",
    "patch_boot_desc": "Include Unity engine tweaks",
    "patch_ggm": "Patch GlobalGameManagers",
    "patch_ggm_desc": "Include QualitySettings binary patch",
    "self_destruct": "Self-Destruct After Launch",
    "self_destruct_desc": "Kills this tweaker 3 seconds after Steam accepts the launch command",
    "prepare_env": "Prepare Environment",
    "launch_stealth": "Launch & Stealth",
    "restore_all_files": "Restore All Files",
    "layer3_memory": "Layer 3 � Runtime Memory",
    "unsafe": "UNSAFE",
    "layer3_desc": "Require anti-cheat ALREADY DISABLED. Open handle to running game and patch executable memory. Kernel-level AC = instant ban. Use only in offline/private servers.",
    "load_patch_db": "Load Patch DB",
    "apply_all_ready": "Apply All Ready",
    "process_optimization": "Process Optimization",
    "high_priority": "High Priority",
    "high_priority_desc": "Set SCPSL.exe to High",
    "realtime": "Realtime",
    "realtime_desc": "Maximum scheduling priority",
    "physical_cores": "Physical Cores",
    "physical_cores_desc": "Disable HT/SMT cores",
    "clear_ram": "Clear RAM",
    "clear_ram_desc": "Trim working sets",
    "timer_05ms": "Timer 0.5ms",
    "timer_05ms_desc": "Reduce input latency",
    "kill_bloat": "Kill Bloat",
    "kill_bloat_desc": "Stop unnecessary services",
    "system_tweaks": "System Tweaks",
    "persistent": "PERSISTENT",
    "game_mode": "Game Mode",
    "game_mode_desc": "Windows Game Mode for foreground priority",
    "disable_gamebar": "Disable Game Bar",
    "disable_gamebar_desc": "Turns off Xbox overlay and DVR",
    "disable_core_parking": "Disable Core Parking",
    "disable_core_parking_desc": "Keeps CPU cores awake",
    "high_perf_plan": "High Performance Plan",
    "high_perf_plan_desc": "Maximum CPU frequency scaling",
    "disable_fso": "Disable Fullscreen Optimizations",
    "disable_fso_desc": "Legacy fullscreen for SCPSL.exe",
    "disable_hpet": "Disable HPET",
    "disable_hpet_desc": "Lower timer latency for gaming",
    "disable_nagle": "Disable Nagle",
    "disable_nagle_desc": "TCP NoDelay for lower ping",
    "disable_sysmain": "Disable SysMain",
    "disable_sysmain_desc": "Stop Superfetch background I/O",
    "disable_visual_effects": "Disable Visual Effects",
    "disable_visual_effects_desc": "Best performance mode for Windows",
    "rkn_bypass": "RKN Bypass",
    "bypass_not_active": "Bypass not active",
    "bypass_active": "Bypass ACTIVE",
    "zapret_detected": "Zapret detected",
    "network_diagnostics": "Network Diagnostics",
    "network_diagnostics_desc": "Check connectivity to game servers, DNS, and detect conflicts with other bypass tools.",
    "run_diagnostics": "Run Diagnostics",
    "auto_reset_rkn": "Auto-Reset If No Internet",
    "report_issue_desc": "Describe the problem. A full diagnostic report will be generated and sent to Discord.",
    "report_placeholder": "What went wrong?",
    "rkn_desc": "Routes Steam and SCP:SL traffic around Russian ISP blocks via Cloudflare DNS and custom hosts entries.",
    "rkn_analysis": "Bypass Analysis",
    "rkn_analysis_desc": "System analysis to find the best bypass method for your network.",
    "analyze_system": "Analyze System",
    "generate_zapret": "Generate Zapret Config",
    "custom_hosts_title": "Custom Hosts",
    "custom_hosts_desc": "Add your own hosts entries (one per line: IP domain).",
    "apply_custom_hosts": "Apply Custom Hosts",
    "reset_custom_hosts": "Reset Custom",
    "activate_bypass": "Activate Bypass",
    "deactivate": "Deactivate",
    "what_changed": "What is changed",
    "custom_hosts": "Custom hosts entries",
    "cloudflare_dns": "Cloudflare DNS (1.1.1.1)",
    "winhttp_proxy": "WinHTTP proxy reset",
    "app_info": "Application Info",
    "version": "Version",
    "game_path": "Game Path",
    "game_status": "Game Status",
    "backup_manager": "Backup Manager",
    "create_backup": "Create Backup",
    "restore_latest": "Restore Latest",
    "report_issue": "Report Issue",
    "generate_report": "Generate Report",
    "send_report_discord": "Send to Discord",
    "discord_integration": "Discord Integration",
    "discord_integration_desc": "Send reports and notifications to a Discord channel via webhook.",
    "discord_logs_webhook": "Dev Logs / Crashes",
    "discord_reports_webhook": "Player Reports (fallback if hardcoded is empty)",
    "steam_auth": "Steam Account",
    "steam_auth_desc": "Sign in with Steam to save your settings and access all features.",
    "login_with_steam": "Login with Steam",
    "logout": "Logout",
    "steam_auth_pending": "Waiting for Steam authorization...",
    "test_webhook": "Test Webhook",
    "actions": "Actions",
    "open_game_folder": "Open Game Folder",
    "refresh_status": "Refresh Status",
    "status_ready": "Ready",
    "status_unsaved": "Unsaved changes",
    "save_config": "Save Config",
    "memory_no_shadows": "No Shadows",
    "memory_no_shadows_desc": "NOPs the shadow rendering pipeline. Massive GPU savings.",
    "memory_no_fog": "No Fog / Volumetrics",
    "memory_no_fog_desc": "Kills atmospheric fog calculations.",
    "memory_fps_unlock": "FPS Unlock",
    "memory_fps_unlock_desc": "Removes the hard 60/120/144 fps cap inside Unity's main loop.",
    "memory_no_postprocess": "No Post-Process",
    "memory_no_postprocess_desc": "Disables Bloom, SSAO, Motion Blur, DoF in one go.",
    "memory_fov": "FOV Changer",
    "memory_fov_desc": "Patches Camera::get_fieldOfView setter so you can force any FOV.",
    "memory_no_blood": "No Blood / Decals",
    "memory_no_blood_desc": "Disables blood splatter and decal projection. Saves GPU fill-rate and CPU physics.",
    "memory_no_ragdolls": "No Ragdolls",
    "memory_no_ragdolls_desc": "Kills Ragdoll::Update. Bodies instantly snap to ground pose instead of simulating physics. Huge CPU savings in firefights.",
    "memory_no_particles": "No Particles",
    "memory_no_particles_desc": "NOPs ParticleSystem::Update and ::Render. No smoke, sparks, muzzle flash, blood mist.",
    "memory_no_reflections": "No Reflections",
    "memory_no_reflections_desc": "Disables all ReflectionProbe rendering. Turns shiny surfaces into flat matte. Big GPU win in indoor maps.",
    "memory_fast_anim": "Fast Animations (TimeScale)",
    "memory_fast_anim_desc": "Patches Time::get_timeScale to return 2.0. EVERYTHING moves 2x faster including your character. This is a gameplay cheat, not just FPS.",
    "memory_lod": "LOD Override (Lowest)",
    "memory_lod_desc": "Forces LODGroup to always select the lowest quality mesh. Distant players and objects become blocky but render cheap.",
    "graphics_quality": "Graphics Quality",
    "shadow_distance": "Shadow Distance",
    "shadow_cascades": "Shadow Cascades",
    "advanced": "Advanced",
    "lod_bias": "LOD Bias",
    "particle_budget": "Particle Budget",
    "anisotropic_filtering": "Anisotropic Filtering",
    "soft_particles": "Soft Particles",
    "language": "Language",
    "tag_ready": "Ready",
    "tag_placeholder": "Placeholder",
    "apply_patch": "Apply Patch",
    "tooltip_graphics_quality": "Overall rendering quality. Lower = more FPS.",
    "tooltip_draw_distance": "How far you can see. Lower values boost FPS significantly.",
    "tooltip_texture_quality": "Texture resolution. Lower = less VRAM usage.",
    "tooltip_shadow_quality": "Shadow detail. Major FPS impact.",
    "tooltip_anti_aliasing": "MSAA level. 0 = off, 2/4/8 = sample count. Higher = smoother edges, lower FPS.",
    "tooltip_fps_limit": "Cap max FPS. 0 = unlimited. Helps with overheating.",
    "tooltip_vsync": "Syncs FPS with monitor refresh. Adds input lag.",
    "tooltip_anisotropic_filtering": "Sharpens textures at angles. Minor FPS cost.",
    "tooltip_soft_particles": "Smooth particle edges. Disable for more FPS.",
    "tooltip_show_blood": "Blood splatter effects. Disable for clarity.",
    "tooltip_ragdoll_cleanup": "Auto-remove dead bodies. More FPS in fights.",
    "tooltip_master_volume": "Overall game volume.",
    "tooltip_noise_suppression": "Filters mic background noise. Uses CPU.",
    "tab_home": "Home",
    "tab_performance": "Performance",
    "tab_advanced": "Advanced",
    "tab_tools": "Tools",
    "home_welcome": "Welcome to MatrixHole-Engine",
    "home_desc": "Optimize your game in 3 simple steps. Everything here is safe � no files will be modified unless you go to the Advanced tab.",
    "home_step1": "Choose Your Graphics Preset",
    "home_step2": "Launch the Game",
    "home_step3": "Protect Your Settings",
    "recommended_badge": "RECOMMENDED",
    "preset_max_fps_desc": "Lowest quality, highest frames",
    "preset_balanced_desc": "Good quality & performance",
    "preset_quality_desc": "Best visuals, lower FPS",
    "quick_tools": "Quick Tools",
    "panic_reset_title": "Something went wrong?",
    "panic_reset_desc": "Instantly undo every change and restore original game files. Use this if the game crashes or behaves strangely after tweaking.",
    "full_reset_btn": "Undo Everything (Full Reset)",
    "soft_reset_btn": "Soft Reset (Disable tweaks only)",
    "advanced_graphics": "Advanced Graphics",
    "game_cleanup": "Game Cleanup",
    "game_cleanup_desc": "Delete temporary files to free up disk space.",
    "clean": "Clean",
    "clean_all": "Clean All",
    "conflict_detector": "Conflict Detector",
    "conflict_detector_desc": "Scan for conflicting software: RTSS, Cheat Engine, x64dbg, Process Hacker.",
    "scan_now": "Scan Now",
    "focus_assist": "Focus Assist",
    "focus_assist_desc": "Enable Windows Do Not Disturb mode before gaming.",
    "enable_dnd": "Enable DND",
    "disable_dnd": "Disable DND",
    "push_notifications": "Push Notifications",
    "push_notifications_desc": "Monitor favorite servers and get notified when a slot opens.",
    "profile_manager": "Profile Manager",
    "profile_manager_desc": "Save and switch between configuration presets.",
    "create_profile": "Create Profile",
    "refresh": "Refresh",
    "disk_space": "Disk Space",
    "check_disk": "Check Disk",
    "diagnostics": "Diagnostics",
    "export_diagnostics": "Export Diagnostics ZIP",
    "check_dependencies": "Check Dependencies",
    "benchmark": "Benchmark",
    "benchmark_desc": "Measure FPS and frametime while playing. Get performance recommendations.",
    "start_benchmark": "Start Benchmark",
    "stop_benchmark": "Stop",
    "console_commands": "Console Commands",
    "console_commands_desc": "Send commands to the game via DLL hook. Requires active DLL injection.",
    "send": "Send",
    "launch_param_builder": "Launch Param Builder",
    "launch_param_builder_desc": "Visual constructor for Unity/Steam launch flags. Check boxes and the command line is built automatically.",
    "file_modifications": "Modify Game Files",
    "patch_game_binary": "Patch Game Binary",
    "stealth_launch": "Stealth Launch",
    "runtime_memory_patches": "Runtime Memory Patches",
    "show_advanced": "Show Advanced",
    "hide_advanced": "Hide Advanced",
    "advanced_system_tweaks": "Advanced System Tweaks",
    "advanced_system_tweaks_desc": "These change Windows settings. They can help FPS/ping, but may affect other apps. All are reversible.",
    "safe_tweaks": "Quick Performance Boosts",
    "safe_tweaks_desc": "These tweaks are safe and reversible. They help Windows give more resources to the game.",
    "windows_game_tweaks": "Windows Game Tweaks",
    "windows_game_tweaks_desc": "Built-in Windows features for better gaming performance.",
    "discord_connect": "Connect Discord",
    "discord_disconnect": "Disconnect",
    "discord_connected": "Connected",
    "discord_not_connected": "Not connected",
    "discord_rich_presence": "Rich Presence",
    "discord_rich_presence_desc": "Show your game status in Discord profile.",
    "discord_status": "Status",
    "gate_title": "Access by Invitation Only",
    "gate_desc": "This tool is exclusive to verified Discord server members. Login with Discord to continue.",
    "discord_account": "Discord Account",
    "discord_auth_desc": "Sign in with Discord to access the app.",
    "steam_link": "Steam Link",
    "link_steam": "Link Steam",
    "unlink_steam": "Unlink",
    "steam_link_desc": "Link your Steam account to enable full functionality.",
}
