import re

# Quality manual translations for visible UI strings
MANUAL_RU = {
    "tab_graphics": "Графика",
    "tab_gameplay": "Геймплей",
    "tab_audio": "Аудио",
    "tab_launch": "Запуск",
    "tab_cheats": "Читы",
    "tab_system": "Система",
    "tab_network": "Сеть",
    "tab_settings": "Настройки",
    "tab_performance": "Производительность",
    "tab_advanced": "Продвинутое",
    "tab_tools": "Инструменты",
    "tab_home": "Главная",
    "graphics_presets": "Пресеты графики",
    "preset_max_fps": "Макс FPS",
    "preset_balanced": "Баланс",
    "preset_quality": "Качество",
    "visual_settings": "Визуальные настройки",
    "draw_distance": "Дальность прорисовки",
    "camera_fog": "Туман камеры",
    "texture_quality": "Качество текстур",
    "anti_aliasing": "Сглаживание",
    "shadow_quality": "Качество теней",
    "fps_limit": "Лимит FPS (0 = выкл)",
    "effects": "Эффекты",
    "shadows": "Тени",
    "bloom": "Свечение",
    "ssao": "SSAO",
    "motion_blur": "Размытие движения",
    "ambient_occlusion": "Ambient Occlusion",
    "depth_of_field": "Глубина резкости",
    "chromatic_aberration": "Хроматическая аберрация",
    "vsync": "Вертикальная синхронизация",
    "show_blood": "Показывать кровь",
    "ragdoll_cleanup": "Очистка рэгдоллов",
    "flashlight_shadows": "Тени фонарика",
    "ragdoll_limit": "Лимит рэгдоллов",
    "audio_levels": "Уровни звука",
    "master_volume": "Общая громкость",
    "sfx_volume": "Громкость эффектов",
    "voice_volume": "Громкость голоса",
    "music_volume": "Громкость музыки",
    "voice": "Голосовой чат",
    "noise_suppression": "Подавление шума",
    "noise_suppression_desc": "Отключите для меньшей нагрузки на CPU",
    "voice_ns_level": "Уровень подавления шума",
    "steam_launch_options": "Параметры запуска Steam",
    "force_dx11": "Форсировать DirectX 11",
    "fastest_quality": "Макс. производительность",
    "windowed_borderless": "Оконный без рамок",
    "disable_gpu_skinning": "Отключить GPU Skinning",
    "force_vulkan": "Форсировать Vulkan",
    "force_opengl": "Форсировать OpenGL",
    "no_log": "Без логов",
    "no_joy": "Отключить джойстик",
    "high_priority_launch": "Высокий приоритет",
    "malloc_system": "Системный аллокатор",
    "use_all_cores": "Использовать все ядра",
    "custom_args": "Кастомные аргументы",
    "save_launch_options": "Сохранить параметры запуска",
    "launch_game": "Запустить игру",
    "layer1_file_nukes": "Слой 1 — Модификация файлов",
    "safe": "БЕЗОПАСНО",
    "layer1_desc": "Изменяет файлы игры на диске ДО запуска. Античит ещё не работает — он этого не видит. Steam может откатить файлы после обновления; примените повторно.",
    "anticheat_bypass": "Обход античита",
    "anticheat_bypass_desc": "Заменяет SL-AC.dll на заглушку. Античит не загружается.",
    "disable_crash_handler": "Отключить обработчик крашей",
    "disable_crash_handler_desc": "Запрещает запуск UnityCrashHandler. Меньше фоновых процессов.",
    "disable_analytics": "Отключить аналитику",
    "disable_analytics_desc": "Удаляет Unity analytics DLL. Останавливает сбор телеметрии.",
    "bootconfig_nuke": "Boot.config мод",
    "bootconfig_nuke_desc": "Агрессивный GC, без single-instance блокировки, многопоточный рендер.",
    "ggm_destroyer": "GlobalGameManagers мод",
    "ggm_destroyer_desc": "Бинарный патч Unity QualitySettings. Ноль теней, без AA, без vsync, агрессивный LOD.",
    "layer1b_hex": "Слой 1b — Hex GameAssembly",
    "nuclear": "ЯДЕРНЫЙ",
    "layer1b_desc": "Хекс-патчит скомпилированный IL2CPP бинарник (GameAssembly.dll) на диске. Неправильный паттерн = мгновенный краш. Обновляйте паттерны через x64dbg.",
    "analyze_binary": "Анализировать бинарник",
    "apply_hex_patches": "Применить хекс-патчи",
    "restore_backup": "Восстановить бэкап",
    "layer2_launch": "Слой 2 — Скрытый запуск",
    "layer2_desc": "Подготовка + запуск в один клик. Опционально самоуничтожение твикера после запуска, чтобы античит не нашёл процесс.",
    "patch_ac": "Патч античита",
    "patch_ac_desc": "Включить замену SL-AC.dll",
    "patch_boot": "Патч Boot.config",
    "patch_boot_desc": "Включить твики движка Unity",
    "patch_ggm": "Патч GlobalGameManagers",
    "patch_ggm_desc": "Включить бинарный патч QualitySettings",
    "self_destruct": "Самоуничтожение после запуска",
    "self_destruct_desc": "Убивает твикер через 3 секунды после принятия команды запуска Steam",
    "prepare_env": "Подготовить окружение",
    "launch_stealth": "Запустить скрытно",
    "restore_all_files": "Восстановить все файлы",
    "layer3_memory": "Слой 3 — Память во время игры",
    "unsafe": "ОПАСНО",
    "layer3_desc": "Требует, чтобы античит УЖЕ БЫЛ ОТКЛЮЧЁН. Открывает хендл к запущенной игре и патчит память. Ядерный античит = мгновенный бан. Только для офлайн/приватных серверов.",
    "load_patch_db": "Загрузить базу патчей",
    "apply_all_ready": "Применить все готовые",
    "process_optimization": "Оптимизация процессов",
    "high_priority": "Высокий приоритет",
    "high_priority_desc": "Установить SCPSL.exe в High",
    "realtime": "Realtime",
    "realtime_desc": "Максимальный приоритет планирования",
    "physical_cores": "Физические ядра",
    "physical_cores_desc": "Отключить HT/SMT ядра",
    "clear_ram": "Очистить RAM",
    "clear_ram_desc": "Очистить рабочие наборы",
    "timer_05ms": "Таймер 0.5мс",
    "timer_05ms_desc": "Снизить задержку ввода",
    "kill_bloat": "Убить хлам",
    "kill_bloat_desc": "Остановить ненужные сервисы",
    "system_tweaks": "Системные твики",
    "persistent": "ПОСТОЯННЫЕ",
    "game_mode": "Игровой режим",
    "game_mode_desc": "Windows Game Mode для приоритета foreground",
    "disable_gamebar": "Отключить Game Bar",
    "disable_gamebar_desc": "Отключает Xbox оверлей и DVR",
    "disable_core_parking": "Отключить Core Parking",
    "disable_core_parking_desc": "Держит ядра CPU активными",
    "high_perf_plan": "План высокой производительности",
    "high_perf_plan_desc": "Максимальная частота CPU",
    "disable_fso": "Отключить Fullscreen Optimizations",
    "disable_fso_desc": "Классический фулскрин для SCPSL.exe",
    "disable_hpet": "Отключить HPET",
    "disable_hpet_desc": "Меньшая задержка таймера для игр",
    "disable_nagle": "Отключить Nagle",
    "disable_nagle_desc": "TCP NoDelay для меньшего пинга",
    "disable_sysmain": "Отключить SysMain",
    "disable_sysmain_desc": "Остановить фоновый ввод-вывод Superfetch",
    "disable_visual_effects": "Отключить визуальные эффекты",
    "disable_visual_effects_desc": "Режим максимальной производительности Windows",
    "rkn_bypass": "Обход РКН",
    "bypass_not_active": "Обход не активен",
    "bypass_active": "Обход АКТИВЕН",
    "zapret_detected": "Zapret обнаружен",
    "network_diagnostics": "Сетевая диагностика",
    "network_diagnostics_desc": "Проверка связи с игровыми серверами, DNS и обнаружение конфликтов с другими обходами.",
    "run_diagnostics": "Запустить диагностику",
    "auto_reset_rkn": "Авто-сброс при отсутствии интернета",
    "report_issue_desc": "Опишите проблему. Будет создан полный диагностический отчёт и отправлен в Discord.",
    "report_placeholder": "Что пошло не так?",
    "rkn_desc": "Маршрутизирует трафик Steam и SCP:SL в обход блокировок российских провайдеров через Cloudflare DNS и кастомные записи hosts.",
    "rkn_analysis": "Анализ обхода",
    "rkn_analysis_desc": "Системный анализ для поиска лучшего метода обхода для вашей сети.",
    "analyze_system": "Анализировать систему",
    "generate_zapret": "Сгенерировать конфиг Zapret",
    "custom_hosts_title": "Кастомные хосты",
    "custom_hosts_desc": "Добавьте свои записи hosts (по одной на строку: IP домен).",
    "apply_custom_hosts": "Применить кастомные хосты",
    "reset_custom_hosts": "Сбросить кастомные",
    "activate_bypass": "Активировать обход",
    "deactivate": "Деактивировать",
    "what_changed": "Что изменено",
    "custom_hosts": "Кастомные записи hosts",
    "cloudflare_dns": "Cloudflare DNS (1.1.1.1)",
    "winhttp_proxy": "Сброс WinHTTP прокси",
    "app_info": "Информация о приложении",
    "version": "Версия",
    "game_path": "Путь к игре",
    "game_status": "Статус игры",
    "backup_manager": "Менеджер бэкапов",
    "create_backup": "Создать бэкап",
    "restore_latest": "Восстановить последний",
    "report_issue": "Сообщить о проблеме",
    "generate_report": "Сгенерировать отчёт",
    "send_report_discord": "Отправить в Discord",
    "discord_integration": "Интеграция Discord",
    "discord_integration_desc": "Отправка отчётов и уведомлений в канал Discord через вебхук.",
    "discord_logs_webhook": "Логи / Краши",
    "discord_reports_webhook": "Репорты игроков",
    "steam_auth": "Аккаунт Steam",
    "steam_auth_desc": "Войдите через Steam, чтобы сохранять настройки и получить доступ ко всем функциям.",
    "login_with_steam": "Войти через Steam",
    "logout": "Выйти",
    "steam_auth_pending": "Ожидание авторизации Steam...",
    "test_webhook": "Тест вебхука",
    "actions": "Действия",
    "open_game_folder": "Открыть папку игры",
    "refresh_status": "Обновить статус",
    "status_ready": "Готово",
    "status_unsaved": "Есть несохранённые изменения",
    "save_config": "Сохранить конфиг",
    "memory_no_shadows": "Без теней",
    "memory_no_shadows_desc": "NOP теневого пайплайна. Огромная экономия GPU.",
    "memory_no_fog": "Без тумана",
    "memory_no_fog_desc": "Убивает атмосферный туман.",
    "memory_fps_unlock": "Разблокировка FPS",
    "memory_fps_unlock_desc": "Снимает жёсткий лимит 60/120/144 FPS в главном цикле Unity.",
    "memory_no_postprocess": "Без пост-процесса",
    "memory_no_postprocess_desc": "Отключает Bloom, SSAO, Motion Blur, DoF одним махом.",
    "memory_fov": "Изменение FOV",
    "memory_fov_desc": "Патчит Camera::get_fieldOfView сеттер, чтобы форсировать любой FOV.",
    "memory_no_blood": "Без крови",
    "memory_no_blood_desc": "Отключает брызги крови и декали. Экономит GPU fill-rate и CPU физику.",
    "memory_no_ragdolls": "Без рэгдоллов",
    "memory_no_ragdolls_desc": "Убивает Ragdoll::Update. Тела мгновенно прилипают к земле вместо симуляции физики. Огромная экономия CPU в перестрелках.",
    "memory_no_particles": "Без частиц",
    "memory_no_particles_desc": "NOP ParticleSystem::Update и ::Render. Никакого дыма, искр, дульной вспышки, кровавого тумана.",
    "memory_no_reflections": "Без отражений",
    "memory_no_reflections_desc": "Отключает ReflectionProbe. Блестящие поверхности становятся матовыми. Большой выигрыш GPU на индор-картах.",
    "memory_fast_anim": "Быстрая анимация",
    "memory_fast_anim_desc": "Патчит Time::get_timeScale на 2.0. ВСЁ движется в 2 раза быстрее, включая вашего персонажа. Это чит, а не просто FPS.",
    "home_welcome": "Добро пожаловать в MatrixHole-Engine",
    "home_desc": "Оптимизируйте игру в 3 простых шага. Всё здесь безопасно — файлы не будут изменены, пока вы не перейдёте во вкладку Продвинутое.",
    "home_step1": "Выберите пресет графики",
    "recommended_badge": "РЕКОМЕНДУЕТСЯ",
    "preset_max_fps_desc": "Минимальное качество, максимальный FPS",
    "preset_balanced_desc": "Хорошее качество и производительность",
    "preset_quality_desc": "Лучшая картинка, меньше FPS",
    "home_step2": "Запустите игру",
    "home_step3": "Защитите настройки",
    "panic_reset_title": "Что-то пошло не так?",
    "panic_reset_desc": "Мгновенно отменить все изменения и восстановить оригинальные файлы игры. Используйте, если игра крашится или ведёт себя странно после твиков.",
    "full_reset_btn": "Откатить всё (Полный сброс)",
    "soft_reset_btn": "Мягкий сброс (Только отключить твики)",
    "quick_tools": "Быстрые инструменты",
    "advanced_graphics": "Продвинутая графика",
    "effects": "Эффекты",
    "safe_tweaks": "Быстрый буст производительности",
    "windows_game_tweaks": "Игровые твики Windows",
    "file_modifications": "Модификация файлов",
    "patch_game_binary": "Патч бинарника игры",
    "stealth_launch": "Скрытый запуск",
    "runtime_memory_patches": "Патчи памяти во время игры",
    "gate_title": "Доступ по приглашению",
    "gate_desc": "Этот инструмент только для верифицированных членов Discord-сервера. Войдите через Discord, чтобы продолжить.",
    "discord_connect": "Подключить Discord",
    "discord_auth_desc": "Войдите через Discord для доступа к приложению.",
    "discord_disconnect": "Отключить",
    "account": "Аккаунт",
    "steam_link_desc": "Привяжите Steam-аккаунт для полного функционала.",
    "link_steam": "Привязать Steam",
    "unlink_steam": "Отвязать",
    "language": "Язык",
    "profile_manager": "Менеджер профилей",
    "profile_manager_desc": "Сохраняйте и переключайтесь между пресетами конфигурации.",
    "diagnostics": "Диагностика",
    "disk_space": "Место на диске",
    "game_cleanup": "Очистка игры",
    "focus_assist": "Фокусировка",
    "focus_assist_desc": "Включите режим «Не беспокоить» перед игрой.",
    "enable_dnd": "Включить DND",
    "disable_dnd": "Отключить DND",
    "push_notifications": "Push-уведомления",
    "push_notifications_desc": "Следите за серверами и получайте уведомления о свободных слотах.",
    "conflict_detector": "Детектор конфликтов",
    "conflict_detector_desc": "Сканирование конфликтующего ПО: RTSS, Cheat Engine, x64dbg, Process Hacker.",
    "scan_now": "Сканировать",
    "benchmark": "Бенчмарк",
    "benchmark_desc": "Измерение FPS и frametime во время игры. Рекомендации по производительности.",
    "report_issue": "Сообщить о проблеме",
    "discord_rich_presence": "Rich Presence",
    "discord_rich_presence_desc": "Показывать игровой статус в профиле Discord.",
    "discord_not_connected": "Не подключено",
    "rkn_bypass": "Обход РКН",
    "what_changed": "Что изменено",
    "custom_hosts_title": "Кастомные хосты",
    "rkn_analysis": "Анализ обхода",
    "rkn_analysis_desc": "Системный анализ для поиска лучшего метода обхода.",
    "network_diagnostics": "Сетевая диагностика",
    "network_diagnostics_desc": "Проверка связи с игровыми серверами, DNS и обнаружение конфликтов.",
}

with open('wwwroot/js/i18n.js', 'r', encoding='utf-8') as f:
    content = f.read()

en_start = content.find('"en":')
ru_start = content.find('"ru":', en_start)
pl_start = content.find('"pl":', ru_start)
if pl_start == -1:
    pl_start = len(content)

en_section = content[en_start:ru_start]
pairs = re.findall(r'"([^"]+)":\s*"([^"]*)"', en_section)

ru_lines = ['  "ru": {']
for key, en_value in pairs:
    ru_value = MANUAL_RU.get(key, en_value)
    ru_value = ru_value.replace('"', '\\"')
    ru_lines.append(f'    "{key}": "{ru_value}",')

if ru_lines[-1].endswith(','):
    ru_lines[-1] = ru_lines[-1][:-1]
ru_lines.append('  },')
new_ru_section = '\r\n'.join(ru_lines) + '\r\n'

new_content = content[:ru_start] + new_ru_section + content[pl_start:]

with open('wwwroot/js/i18n.js', 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f'Done. Manual translations: {len(MANUAL_RU)} / {len(pairs)}')
