PL = {
    "account": "Konto",
    "tab_graphics": "Grafika",
    "tab_gameplay": "Rozgrywka",
    "tab_audio": "Audio",
    "tab_launch": "Uruchomienie",
    "tab_cheats": "DLL Inject",
    "tab_system": "System",
    "tab_network": "Siec",
    "tab_settings": "Ustawienia",
    "graphics_presets": "Presety graficzne",
    "preset_max_fps": "Max FPS",
    "preset_balanced": "Zbalansowany",
    "preset_quality": "Jakosc",
    "visual_settings": "Ustawienia wizualne",
    "draw_distance": "Odleglosc renderowania",
    "camera_fog": "Mgla kamery",
    "texture_quality": "Jakosc tekstur",
    "anti_aliasing": "Antyaliasing",
    "shadow_quality": "Jakosc cieni",
    "fps_limit": "Limit FPS (0 = wyl.)",
    "effects": "Efekty",
    "shadows": "Cienie",
    "bloom": "Bloom",
    "ssao": "SSAO",
    "motion_blur": "Rozmycie ruchu",
    "ambient_occlusion": "Ambient Occlusion",
    "depth_of_field": "Glebia ostrosci",
    "chromatic_aberration": "Aberracja chromatyczna",
    "vsync": "Synchronizacja pionowa",
    "show_blood": "Pokazuj krew",
    "ragdoll_cleanup": "Czyszczenie ragdollow",
    "flashlight_shadows": "Cienie latarki",
    "ragdoll_limit": "Limit ragdollow",
    "audio_levels": "Poziomy dzwieku",
    "master_volume": "Glosnosc ogolna",
    "sfx_volume": "Glosnosc efektow",
    "voice_volume": "Glosnosc glosu",
    "music_volume": "Glosnosc muzyki",
    "voice": "Glos",
    "noise_suppression": "Tlumienie szumow",
    "noise_suppression_desc": "Wylacz dla mniejszego obciazenia CPU",
    "voice_ns_level": "Poziom tlumienia szumow",
    "steam_launch_options": "Opcje uruchomienia Steam",
    "force_dx11": "Wymus DirectX 11",
    "fastest_quality": "Najnizsza jakosc",
    "windowed_borderless": "Okno bez ramki",
    "disable_gpu_skinning": "Wylacz GPU skinning",
    "force_vulkan": "Wymus Vulkan",
    "force_opengl": "Wymus OpenGL",
    "no_log": "Bez logow",
    "no_joy": "Wylacz joystick",
    "high_priority_launch": "Wysoki priorytet",
    "malloc_system": "Systemowy alokator",
    "use_all_cores": "Wszystkie rdzenie",
    "custom_args": "Niestandardowe argumenty",
    "save_launch_options": "Zapisz opcje uruchomienia",
    "launch_game": "Uruchom gre",
    "layer1_file_nukes": "Warstwa 1 � Plikowe bomby",
    "safe": "BEZPIECZNE",
    "layer1_desc": "Modyfikuje pliki gry na dysku PRZED uruchomieniem. Anty-cheat jeszcze nie dziala � tego nie widzi. Steam moze przywrocic pliki po aktualizacji; zastosuj ponownie po patchach.",
    "anticheat_bypass": "Obejscie anty-cheata",
    "anticheat_bypass_desc": "Zastepuje SL-AC.dll atrapa. AC nigdy sie nie laduje.",
    "disable_crash_handler": "Wylacz Crash Handler",
    "disable_crash_handler_desc": "Blokuje UnityCrashHandler. Mniej szumu w tle.",
    "disable_analytics": "Wylacz Analytics",
    "disable_analytics_desc": "Usuwa Unity analytics DLL. Zatrzymuje telemetrie.",
    "bootconfig_nuke": "Bomba Boot.config",
    "bootconfig_nuke_desc": "Agresywne GC, bez blokady single-instance, wielowatkowy renderer.",
    "ggm_destroyer": "Niszczyciel GlobalGameManagers",
    "ggm_destroyer_desc": "Binarny patch Unity QualitySettings. Zero cieni, brak AA, brak vsync, agresywny LOD.",
    "layer1b_hex": "Warstwa 1b � Hex GameAssembly",
    "nuclear": "JADROWY",
    "layer1b_desc": "Hex-patchuje skompilowany binarny IL2CPP (GameAssembly.dll) na dysku. Zly wzorzec = natychmiastowy crash przy starcie. Zaktualizuj wzorce przez x64dbg przed uzyciem.",
    "analyze_binary": "Analizuj binarny",
    "apply_hex_patches": "Zastosuj hex patche",
    "restore_backup": "Przywroc kopie zapasowa",
    "layer2_launch": "Warstwa 2 � Ukryte uruchomienie",
    "layer2_desc": "Przygotowanie + uruchomienie jednym kliknieciem. Opcjonalnie samozniszczenie tweaker'a, aby w pamieci nie zostal proces do skanowania przez anty-cheat.",
    "patch_ac": "Patch anty-cheata",
    "patch_ac_desc": "Uwzglednij zamiennik SL-AC.dll",
    "patch_boot": "Patch Boot.config",
    "patch_boot_desc": "Uwzglednij tweak'i silnika Unity",
    "patch_ggm": "Patch GlobalGameManagers",
    "patch_ggm_desc": "Uwzglednij binarny patch QualitySettings",
    "self_destruct": "Samozniszczenie po uruchomieniu",
    "self_destruct_desc": "Zabija tweaker'a 3 sekundy po zaakceptowaniu komendy uruchomienia Steam",
    "prepare_env": "Przygotuj srodowisko",
    "launch_stealth": "Uruchom ukrycie",
    "restore_all_files": "Przywroc wszystkie pliki",
    "layer3_memory": "Warstwa 3 � Pamiec w czasie rzeczywistym",
    "unsafe": "NIEBEZPIECZNE",
    "layer3_desc": "Wymaga wczesniejszego WYLACZENIA anty-cheata. Otwiera uchwyt do dzialajacej gry i patchuje wykonywalna pamiec. Kernel-level AC = natychmiastowy ban. Uzywaj tylko na offline/prywatnych serwerach.",
    "load_patch_db": "Zaladuj baze patch'y",
    "apply_all_ready": "Zastosuj wszystkie gotowe",
    "process_optimization": "Optymalizacja procesow",
    "high_priority": "Wysoki priorytet",
    "high_priority_desc": "Ustaw SCPSL.exe na High",
    "realtime": "Realtime",
    "realtime_desc": "Maksymalny priorytet planisty",
    "physical_cores": "Rdzenie fizyczne",
    "physical_cores_desc": "Wylacz rdzenie HT/SMT",
    "clear_ram": "Wyczysc RAM",
    "clear_ram_desc": "Przytnij zbiory robocze",
    "timer_05ms": "Timer 0.5ms",
    "timer_05ms_desc": "Zmniejsz opoznienie wejscia",
    "kill_bloat": "Zabij smieci",
    "kill_bloat_desc": "Zatrzymaj niepotrzebne uslugi",
    "system_tweaks": "Tweak'i systemowe",
    "persistent": "TRWALE",
    "game_mode": "Tryb gry",
    "game_mode_desc": "Tryb gry Windows dla priorytetu foreground",
    "disable_gamebar": "Wylacz Game Bar",
    "disable_gamebar_desc": "Wylacza nakladke Xbox i DVR",
    "disable_core_parking": "Wylacz Core Parking",
    "disable_core_parking_desc": "Utrzymuje rdzenie CPU w gotowosci",
    "high_perf_plan": "Plan wysokiej wydajnosci",
    "high_perf_plan_desc": "Maksymalne skalowanie czestotliwosci CPU",
    "disable_fso": "Wylacz optymalizacje pelnoekranowe",
    "disable_fso_desc": "Legacy pelny ekran dla SCPSL.exe",
    "disable_hpet": "Wylacz HPET",
    "disable_hpet_desc": "Nizsze opoznienie timera dla gier",
    "disable_nagle": "Wylacz Nagle",
    "disable_nagle_desc": "TCP NoDelay dla nizszego pingu",
    "disable_sysmain": "Wylacz SysMain",
    "disable_sysmain_desc": "Zatrzymaj Superfetch I/O w tle",
    "disable_visual_effects": "Wylacz efekty wizualne",
    "disable_visual_effects_desc": "Tryb najlepszej wydajnosci Windows",
    "rkn_bypass": "Obejscie RKN",
    "bypass_not_active": "Obejscie nieaktywne",
    "bypass_active": "Obejscie AKTYWNE",
    "zapret_detected": "Zapret wykryty",
    "network_diagnostics": "Diagnostyka sieci",
    "network_diagnostics_desc": "Sprawdz lacznosc z serwerami gry, DNS i wykryj konflikty z innymi narzedziami obejscia.",
    "run_diagnostics": "Uruchom diagnostyke",
    "auto_reset_rkn": "Auto-reset przy braku internetu",
    "report_issue_desc": "Opisz problem. Pelny raport diagnostyczny zostanie wygenerowany i wyslany na Discord.",
    "report_placeholder": "Co poszlo nie tak?",
    "rkn_desc": "Kieruje ruch Steam i SCP:SL wokol rosyjskich blokad ISP przez Cloudflare DNS i niestandardowe wpisy hosts.",
    "rkn_analysis": "Analiza obejscia",
    "rkn_analysis_desc": "Analiza systemu w celu znalezienia najlepszej metody obejscia dla twojej sieci.",
    "analyze_system": "Analizuj system",
    "generate_zapret": "Generuj konfiguracje Zapret",
    "custom_hosts_title": "Niestandardowe Hosts",
    "custom_hosts_desc": "Dodaj wlasne wpisy hosts (jeden na linie: IP domena).",
    "apply_custom_hosts": "Zastosuj niestandardowe hosts",
    "reset_custom_hosts": "Resetuj niestandardowe",
    "activate_bypass": "Aktywuj obejscie",
    "deactivate": "Dezaktywuj",
    "what_changed": "Co zostalo zmienione",
    "custom_hosts": "Niestandardowe wpisy hosts",
    "cloudflare_dns": "Cloudflare DNS (1.1.1.1)",
    "winhttp_proxy": "Reset proxy WinHTTP",
    "app_info": "Informacje o aplikacji",
    "version": "Wersja",
    "game_path": "Sciezka do gry",
    "game_status": "Status gry",
    "backup_manager": "Menedzer kopii zapasowych",
    "create_backup": "Utworz kopie zapasowa",
    "restore_latest": "Przywroc ostatnia",
    "report_issue": "Zglos problem",
    "generate_report": "Generuj raport",
    "send_report_discord": "Wyslij na Discord",
    "discord_integration": "Integracja Discord",
    "discord_integration_desc": "Wysylaj raporty i powiadomienia na kanal Discord przez webhook.",
    "discord_logs_webhook": "Logi / Crashe",
    "discord_reports_webhook": "Raporty (fallback jesli nie hardcoded)",
    "steam_auth": "Konto Steam",
    "steam_auth_desc": "Zaloguj sie przez Steam, aby zapisac ustawienia i uzyskac dostep do wszystkich funkcji.",
    "login_with_steam": "Zaloguj przez Steam",
    "logout": "Wyloguj",
    "steam_auth_pending": "Oczekiwanie na autoryzacje Steam...",
    "test_webhook": "Testuj Webhook",
    "actions": "Akcje",
    "open_game_folder": "Otworz folder gry",
    "refresh_status": "Odswiez status",
    "status_ready": "Gotowy",
    "status_unsaved": "Niezapisane zmiany",
    "save_config": "Zapisz konfiguracje",
    "memory_no_shadows": "Bez cieni",
    "memory_no_shadows_desc": "Wylacza renderowanie cieni. Ogromna oszczednosc GPU.",
    "memory_no_fog": "Bez mgly / wolumetryki",
    "memory_no_fog_desc": "Zabija obliczenia atmosferycznej mgly.",
    "memory_fps_unlock": "Odblokowanie FPS",
    "memory_fps_unlock_desc": "Usuwa twardy limit 60/120/144 FPS w glownej petli Unity.",
    "memory_no_postprocess": "Bez post-processingu",
    "memory_no_postprocess_desc": "Wylacza Bloom, SSAO, Motion Blur, DoF jednym ruchem.",
    "memory_fov": "Zmiana FOV",
    "memory_fov_desc": "Patchuje setter Camera::get_fieldOfView, aby wymusic dowolne FOV.",
    "memory_no_blood": "Bez krwi / decal'i",
    "memory_no_blood_desc": "Wylacza krwawe plamy i projekcje decal'i. Oszczedza GPU fill-rate i fizyke CPU.",
    "memory_no_ragdolls": "Bez ragdollow",
    "memory_no_ragdolls_desc": "Zabija Ragdoll::Update. Ciala natychmiast przyjmuja pozycje na ziemi zamiast symulowac fizyke. Ogromna oszczednosc CPU w strzelaninach.",
    "memory_no_particles": "Bez czastek",
    "memory_no_particles_desc": "Wylacza ParticleSystem::Update i ::Render. Brak dymu, iskier, blysku lufy, krwawej mgly.",
    "memory_no_reflections": "Bez odbic",
    "memory_no_reflections_desc": "Wylacza renderowanie ReflectionProbe. Blyszczace powierzchnie staja sie plaskie i matowe. Duzy zysk GPU w zamknietych mapach.",
    "memory_fast_anim": "Szybkie animacje (TimeScale)",
    "memory_fast_anim_desc": "Patchuje Time::get_timeScale na 2.0. WSZYSTKO porusza sie 2x szybciej, wlacznie z twoja postacia. To cheat, nie tylko FPS.",
    "memory_lod": "Nadpisanie LOD (najnizsze)",
    "memory_lod_desc": "Wymusza LODGroup zawsze wybierac najnizszy jakosciowy mesh. Oddaleni gracze i obiekty staja sie kanciaste, ale renderuja sie tanio.",
    "graphics_quality": "Jakosc grafiki",
    "shadow_distance": "Odleglosc cieni",
    "shadow_cascades": "Kaskadowanie cieni",
    "advanced": "Zaawansowane",
    "lod_bias": "Bias LOD",
    "particle_budget": "Budzet czastek",
    "anisotropic_filtering": "Filtrowanie anizotropowe",
    "soft_particles": "Miekkie czastki",
    "language": "Jezyk",
    "tag_ready": "Gotowy",
    "tag_placeholder": "Zastepczy",
    "apply_patch": "Zastosuj patch",
    "tooltip_anti_aliasing": "Poziom MSAA. 0 = wylaczone, 2/4/8 = liczba probek. Wyzej = gladsze krawedzie, nizej FPS.",
    "tab_home": "Start",
    "tab_performance": "Wydajnosc",
    "tab_advanced": "Zaawansowane",
    "tab_tools": "Narzedzia",
    "home_welcome": "Witaj w MatrixHole-Engine",
    "home_desc": "Zoptymalizuj gre w 3 prostych krokach. Wszystko tutaj jest bezpieczne � pliki nie zostana zmodyfikowane, chyba ze przejdziesz do zakladki Zaawansowane.",
    "home_step1": "Wybierz preset graficzny",
    "home_step2": "Uruchom gre",
    "home_step3": "Chron swoje ustawienia",
    "recommended_badge": "POLECAMY",
    "preset_max_fps_desc": "Najnizsza jakosc, najwiecej FPS",
    "preset_balanced_desc": "Dobra jakosc i wydajnosc",
    "preset_quality_desc": "Najlepsza grafika, mniej FPS",
    "quick_tools": "Szybkie narzedzia",
    "panic_reset_title": "Cos poszlo nie tak?",
    "panic_reset_desc": "Natychmiast cofnij wszystkie zmiany i przywroc oryginalne pliki gry. Uzyj tego, jesli gra crashuje lub zachowuje sie dziwnie po tweakach.",
    "full_reset_btn": "Cofnij wszystko (Pelny reset)",
    "soft_reset_btn": "Miekki reset (Tylko wylacz tweak'i)",
    "advanced_graphics": "Zaawansowana grafika",
    "game_cleanup": "Czyszczenie gry",
    "game_cleanup_desc": "Usun pliki tymczasowe, aby zwolnic miejsce na dysku.",
    "clean": "Wyczysc",
    "clean_all": "Wyczysc wszystko",
    "conflict_detector": "Detektor konfliktow",
    "conflict_detector_desc": "Skanuj w poszukiwaniu konfliktujacego oprogramowania: RTSS, Cheat Engine, x64dbg, Process Hacker.",
    "scan_now": "Skanuj teraz",
    "focus_assist": "Asystent skupienia",
    "focus_assist_desc": "Wlacz tryb Nie przeszkadzac w Windows przed gra.",
    "enable_dnd": "Wlacz DND",
    "disable_dnd": "Wylacz DND",
    "push_notifications": "Powiadomienia push",
    "push_notifications_desc": "Monitoruj ulubione serwery i otrzymuj powiadomienia, gdy pojawi sie slot.",
    "profile_manager": "Menedzer profili",
    "profile_manager_desc": "Zapisuj i przelaczaj sie miedzy presetami konfiguracji.",
    "create_profile": "Utworz profil",
    "refresh": "Odswiez",
    "disk_space": "Miejsce na dysku",
    "check_disk": "Sprawdz dysk",
    "diagnostics": "Diagnostyka",
    "export_diagnostics": "Eksportuj diagnostyke ZIP",
    "check_dependencies": "Sprawdz zaleznosci",
    "benchmark": "Benchmark",
    "benchmark_desc": "Mierz FPS i czas klatki podczas gry. Uzyskaj rekomendacje dotyczace wydajnosci.",
    "start_benchmark": "Uruchom benchmark",
    "stop_benchmark": "Zatrzymaj",
    "console_commands": "Komendy konsoli",
    "console_commands_desc": "Wysylaj komendy do gry przez hook DLL. Wymaga aktywnej injekcji DLL.",
    "send": "Wyslij",
    "launch_param_builder": "Konstruktor parametrow uruchomienia",
    "launch_param_builder_desc": "Wizualny konstruktor flag uruchomienia Unity/Steam. Zaznacz pola i wiersz polecen zostanie zbudowany automatycznie.",
    "file_modifications": "Modyfikuj pliki gry",
    "patch_game_binary": "Patchuj plik binarny gry",
    "stealth_launch": "Ukryte uruchomienie",
    "runtime_memory_patches": "Patche pamieci w czasie rzeczywistym",
    "show_advanced": "Pokaz zaawansowane",
    "hide_advanced": "Ukryj zaawansowane",
    "advanced_system_tweaks": "Zaawansowane tweak'i systemowe",
    "advanced_system_tweaks_desc": "Te tweak'i zmieniaja ustawienia Windows. Moga pomoc FPS/pingowi, ale moga wplynac na inne aplikacje. Wszystkie sa odwracalne.",
    "safe_tweaks": "Szybkie zwiekszenie wydajnosci",
    "safe_tweaks_desc": "Te tweak'i sa bezpieczne i odwracalne. Pomagaja Windows przydzielic wiecej zasobow grze.",
    "windows_game_tweaks": "Gamingowe tweak'i Windows",
    "windows_game_tweaks_desc": "Wbudowane funkcje Windows dla lepszej wydajnosci gier.",
    "tooltip_anisotropic_filtering": "Wyostrza tekstury pod katami. Niewielki koszt FPS.",
    "tooltip_draw_distance": "Jak daleko widzisz. Nizsze wartosci znacznie zwiekszaja FPS.",
    "tooltip_fps_limit": "Limit maksymalnego FPS. 0 = nieograniczony. Pomaga przy przegrzewaniu.",
    "tooltip_graphics_quality": "Ogolna jakosc renderowania. Nizsza = wiecej FPS.",
    "tooltip_master_volume": "Ogolna glosnosc gry.",
    "tooltip_noise_suppression": "Filtruje szumy tla z mikrofonu. Obciaza CPU.",
    "tooltip_ragdoll_cleanup": "Auto-usuwanie zwlok. Wiecej FPS w walkach.",
    "tooltip_shadow_quality": "Szczegolowosc cieni. Duzy wplyw na FPS.",
    "tooltip_show_blood": "Efekty rozbryzgu krwi. Wylacz dla przejrzystosci.",
    "tooltip_soft_particles": "Gladkie krawedzie czastek. Wylacz dla wiecej FPS.",
    "tooltip_texture_quality": "Rozdzielczosc tekstur. Nizsza = mniej zuzycia VRAM.",
    "tooltip_vsync": "Synchronizuje FPS z odswiezaniem monitora. Dodaje opoznienie wejscia.",
    "discord_connect": "Polacz Discord",
    "discord_disconnect": "Rozlacz",
    "discord_connected": "Polaczony",
    "discord_not_connected": "Nie polaczony",
    "discord_rich_presence": "Rich Presence",
    "discord_rich_presence_desc": "Pokaz status gry w profilu Discord.",
    "discord_status": "Status",
    "gate_title": "Dostep tylko na zaproszenie",
    "gate_desc": "To narzedzie jest tylko dla zweryfikowanych czlonkow serwera Discord. Zaloguj sie przez Discord, aby kontynuowac.",
    "discord_account": "Konto Discord",
    "discord_auth_desc": "Zaloguj sie przez Discord, aby uzyskac dostep do aplikacji.",
    "steam_link": "Powiazanie Steam",
    "link_steam": "Powiaz Steam",
    "unlink_steam": "Odlacz",
    "steam_link_desc": "Polacz konto Steam, aby wlaczyc pelna funkcjonalnosc.",
}
